on:
  push:
    branches:
      - deploy/develop
  workflow_dispatch:

jobs:
  build-and-push-images:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
  
      - name: Build and push Backend
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/bongma-backend:latest
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/bongma-backend:latest
          cache-to: type=inline

      - name: Build and push Frontend
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/bongma-frontend:latest
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/bongma-frontend:latest
          cache-to: type=inline

  deploy:
    needs: build-and-push-images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Add SSH Key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
  
      - name: Add host to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H 115.73.218.193 >> ~/.ssh/known_hosts

      - name: Copy docker-compose to Server
        run: |
          scp docker-compose.yml vutri@115.73.218.193:~/projects/BongMa/
      
      - name: Connect, Pull, and Build Docker
        run: |
          ssh vutri@115.73.218.193 << 'EOF'
            set -e
            cd ~/projects/BongMa
            
            # Khai báo biến
            export DOCKERHUB_USER=${{ secrets.DOCKERHUB_USERNAME }}
            
            # Thêm chữ -E vào sau sudo để nó không làm rơi mất biến DOCKERHUB_USER
            echo "${{ secrets.SSH_PASS }}" | sudo -E -S docker compose pull
            echo "${{ secrets.SSH_PASS }}" | sudo -E -S docker compose up -d
          EOF